version: '3.8'
services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workdir
      - '/workdir/node_modules'
    working_dir: /workdir
    ports:
      - 3000:3000